name: calio
description: "Track calories, meals, and progress easily. Stay fit, eat smart, live better."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  rxdart: ^0.28.0
  flutter_riverpod: ^3.0.0
  provider: ^6.1.5+1
  intl: ^0.20.2 #Used for datetime formate
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  web:
    generate: true
  image_path: "assets/icons/app_icon.png"

